Fix compilation with C++17
libtextclassifier-0.0.1/platform2/libtextclassifier/utils/base/arena.cc:31:14:

error: unused function 'aligned_malloc' [-Werror,-Wunused-function]

static void *aligned_malloc(size_t size, int minimum_alignment) {
             ^

aligned_malloc is only called by AllocateAlignedBytes when
__cpp_aligned_new is not defined.

BUG=b:162949739
TEST=CQ passes

Change-Id: I4802b69e70f21eaae5e4dc6bfca96fcc5bc7bacb
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/libtextclassifier/+/2341941
Reviewed-by: Honglin Yu <honglinyu@chromium.org>
Commit-Queue: Tom Hughes <tomhughes@chromium.org>
Tested-by: Tom Hughes <tomhughes@chromium.org>
Auto-Submit: Tom Hughes <tomhughes@chromium.org>